import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import CursorTracker from '@components/cursorTracker';
import HomeLinks from '@components/homeLinks';
import Galaxy from '@components/galaxy';
import { Button } from '@components/ui/button';
import Linkedin from '@assets/icons/linkedin.svg';
import Github from '@assets/icons/github.svg';
import Link from 'next/link';
import SocialLinks from '@components/socialLinks';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          'min-h-screen bg-gradient-to-b from-[#0c1520] via-[#131f30] to-black md:max-h-screen md:overflow-hidden'
        }
      >
        <CursorTracker />
        <Galaxy />
        <SocialLinks className='hidden md:right-10 md:top-5 md:fixed'/>

        <div className="">{children}</div>
      </body>
    </html>
  );
}
